apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: judgemesh-infra
  labels:
    app: rabbitmq
spec:
  serviceName: rabbitmq-headless
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "15692"
    spec:
      containers:
        - name: rabbitmq
          image: docker.io/rabbitmq:3.13-management
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: judgemesh-infra-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: judgemesh-infra-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: -rabbitmq_prometheus return_per_object_metrics true
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http
            - containerPort: 15692
              name: prom
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 40
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: judgemesh-infra
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
    - name: prom
      port: 15692
      targetPort: 15692
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: judgemesh-infra
spec:
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
