apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-infra-secrets
  namespace: judgemesh-infra
type: Opaque
stringData:
  redis-password: change-me
  rabbitmq-username: judgemesh
  rabbitmq-password: change-me
  nacos-auth-token: change-me
  nacos-identity-value: change-me
