apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-infra-secrets
  namespace: judgemesh-infra
type: Opaque
stringData:
  redis-password: judgemesh
  rabbitmq-username: judgemesh
  rabbitmq-password: judgemesh
  nacos-auth-token: anVkZ2VtZXNoLWxvY2FsLW5hY29zLWF1dGgtdG9rZW4tMzItYnl0ZXM=
  nacos-identity-value: judgemesh-dev-identity
