apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-infra-secrets
  namespace: judgemesh-infra
type: Opaque
stringData:
  redis-password: judgemesh
  rabbitmq-username: judgemesh
  rabbitmq-password: judgemesh
  nacos-auth-token: judgemesh-dev-token
  nacos-identity-value: judgemesh-dev-identity
