apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oj-ingress
  namespace: judgemesh
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: oj.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: gateway, port: { number: 8080 } }
          - path: /ws
            pathType: Prefix
            backend:
              service: { name: gateway, port: { number: 8080 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: frontend, port: { number: 80 } }
