apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-secrets
  namespace: judgemesh-infra
type: Opaque
stringData:
  mysql-username: judgemesh
  mysql-password: judgemesh
  MYSQL_USER: judgemesh
  MYSQL_PASSWORD: judgemesh
  rabbitmq-username: judgemesh
  rabbitmq-password: judgemesh
  RABBITMQ_USER: judgemesh
  RABBITMQ_PASSWORD: judgemesh
  minio-access-key: minioadmin
  minio-secret-key: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
