apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: judge-worker-queue-scaler
  namespace: judgemesh
spec:
  scaleTargetRef:
    name: judge-worker
  pollingInterval: 15
  cooldownPeriod: 300
  minReplicaCount: 3
  maxReplicaCount: 20
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: RABBITMQ_URL
        protocol: amqp
        queueName: submit.queue
        mode: QueueLength
        value: "5"
