apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-secrets
  namespace: judgemesh
type: Opaque
stringData:
  mysql-username: judgemesh
  mysql-password: judgemesh
  MYSQL_USER: judgemesh
  MYSQL_PASSWORD: judgemesh
  redis-password: judgemesh
  REDIS_PASSWORD: judgemesh
  jwt-secret: dev-secret-change-me-32-bytes
  JWT_SECRET: dev-secret-change-me-32-bytes
  seata-tx-group: judgemesh-tx-group
  SEATA_TX_GROUP: judgemesh-tx-group
  rabbitmq-username: judgemesh
  rabbitmq-password: judgemesh
  RABBITMQ_USER: judgemesh
  RABBITMQ_PASSWORD: judgemesh
  minio-access-key: minioadmin
  minio-secret-key: minioadmin
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
