apiVersion: v1
kind: Secret
metadata:
  name: judgemesh-secrets
  namespace: judgemesh
type: Opaque
stringData:
  mysql-username: judgemesh
  mysql-password: change-me
  jwt-secret: change-me
  seata-tx-group: judgemesh-tx-group
  rabbitmq-username: judgemesh
  rabbitmq-password: change-me
  minio-access-key: change-me
  minio-secret-key: change-me
