apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/app-secrets
  - ../../base/infra-app-secrets
  - ../../base/infra-secrets
  - ../../base/nacos
  - ../../base/seata-server
  - ../../base/sentinel-dashboard
  - ../../base/mysql
  - ../../base/minio
  - ../../base/redis
  - ../../base/rabbitmq
  - ../../base/etcd
  - ../../base/cert-manager
  - ../../base/ingress-nginx
  - ../../base/keda
  - ../../base/grafana-dashboards
  - ../../base/monitoring
  - ../../base/gateway
  - ../../base/user-service
  - ../../base/problem-service
  - ../../base/submit-service
  - ../../base/judge-dispatcher
  - ../../base/judge-worker
  - ../../base/frontend
  - ../../base/ingress
  - resilience.yaml

images:
  - name: docker.io/judgemesh/judgemesh-gateway
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judgemesh-gateway
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-user-service
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judgemesh-user-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-problem-service
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judgemesh-problem-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-submit-service
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judgemesh-submit-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-judge-dispatcher
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judgemesh-judge-dispatcher
    newTag: latest
  - name: docker.io/judgemesh/judge-worker
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/judge-worker
    newTag: latest
  - name: docker.io/judgemesh/frontend
    newName: asia-east1-docker.pkg.dev/project-ad762830-bf41-4f10-b00/judgemesh/frontend
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: oj-ingress
      namespace: judgemesh
    patch: |-
      - op: remove
        path: /spec/rules/0/host
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: frontend
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: gateway
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: user-service
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: problem-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: problem-service
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: submit-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: submit-service
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: judge-dispatcher
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: judge-dispatcher
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: Deployment
      name: judge-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/strategy
        value:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
      - op: replace
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: role
                      operator: In
                      values: [judge]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: judge-worker
                  topologyKey: kubernetes.io/hostname
      - op: add
        path: /spec/template/spec/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app: judge-worker
  - target:
      kind: ScaledObject
      name: judge-worker-queue-scaler
    patch: |-
      - op: replace
        path: /spec/minReplicaCount
        value: 3
      - op: replace
        path: /spec/maxReplicaCount
        value: 6
      - op: replace
        path: /spec/cooldownPeriod
        value: 180
      - op: replace
        path: /spec/triggers/0/metadata/value
        value: "4"
  - target:
      kind: StatefulSet
      name: etcd
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: etcd
                  topologyKey: kubernetes.io/hostname
  - target:
      kind: StatefulSet
      name: mysql
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
  - target:
      kind: StatefulSet
      name: minio
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
  - target:
      kind: StatefulSet
      name: nacos
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
  - target:
      kind: StatefulSet
      name: redis
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
  - target:
      kind: StatefulSet
      name: rabbitmq
    patch: |-
      - op: add
        path: /spec/template/spec/affinity
        value:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values: [app]
