apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: judgemesh

resources:
  - ../../base/gateway
  - ../../base/user-service
  - ../../base/problem-service
  - ../../base/submit-service
  - ../../base/judge-dispatcher
  - ../../base/judge-worker
  - ../../base/frontend
  - ../../base/ingress

patches:
  - target: { kind: Deployment, name: gateway }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: user-service }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: problem-service }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: submit-service }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: judge-dispatcher }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: judge-worker }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target: { kind: Deployment, name: frontend }
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
