# helm install skywalking apache/skywalking -n judgemesh-observe --create-namespace -f infra/helm/values/skywalking.yaml
oap:
  storageType: elasticsearch
  replicas: 1
  image:
    tag: 9.7.0
  envoy:
    metricsServiceEnabled: false
  service:
    zipkin:
      enabled: true
    otlp:
      enabled: true
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
ui:
  replicas: 1
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
elasticsearch:
  enabled: true
  minimumMasterNodes: 1
  replicas: 1
  volumeClaimTemplate:
    resources:
      requests:
        storage: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi
