apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/app-secrets
  - ../../base/infra-secrets
  - ../../base/nacos
  - ../../base/redis
  - ../../base/rabbitmq
  - ../../base/etcd
  - ../../base/cert-manager
  - ../../base/ingress-nginx
  - ../../base/keda
  - ../../base/grafana-dashboards
  - ../../base/gateway
  - ../../base/user-service
  - ../../base/problem-service
  - ../../base/submit-service
  - ../../base/judge-dispatcher
  - ../../base/judge-worker
  - ../../base/frontend
  - ../../base/ingress
