apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/namespaces
  - ../../base/app-secrets
  - ../../base/infra-secrets
  - ../../base/nacos
  - ../../base/seata-server
  - ../../base/sentinel-dashboard
  - ../../base/mysql
  - ../../base/minio
  - ../../base/redis
  - ../../base/rabbitmq
  - ../../base/etcd
  - ../../base/cert-manager
  - ../../base/ingress-nginx
  - ../../base/keda
  - ../../base/grafana-dashboards
  - ../../base/monitoring
  - ../../base/gateway
  - ../../base/user-service
  - ../../base/problem-service
  - ../../base/submit-service
  - ../../base/judge-dispatcher
  - ../../base/judge-worker
  - ../../base/frontend
  - ../../base/ingress

images:
  - name: docker.io/judgemesh/judgemesh-gateway
    newName: docker.io/judgemesh/judgemesh-gateway
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-user-service
    newName: docker.io/judgemesh/judgemesh-user-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-problem-service
    newName: docker.io/judgemesh/judgemesh-problem-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-submit-service
    newName: docker.io/judgemesh/judgemesh-submit-service
    newTag: latest
  - name: docker.io/judgemesh/judgemesh-judge-dispatcher
    newName: docker.io/judgemesh/judgemesh-judge-dispatcher
    newTag: latest
  - name: docker.io/judgemesh/judge-worker
    newName: docker.io/judgemesh/judge-worker
    newTag: latest
  - name: docker.io/judgemesh/frontend
    newName: docker.io/judgemesh/frontend
    newTag: latest

patches:
  - target:
      kind: Ingress
      name: oj-ingress
      namespace: judgemesh
    patch: |-
      - op: remove
        path: /spec/rules/0/host
